// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import aws_manager "github.com/paysuper/paysuper-aws-manager"
import context "context"
import mock "github.com/stretchr/testify/mock"
import s3manager "github.com/aws/aws-sdk-go/service/s3/s3manager"

// AwsManagerInterface is an autogenerated mock type for the AwsManagerInterface type
type AwsManagerInterface struct {
	mock.Mock
}

// Download provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AwsManagerInterface) Download(_a0 context.Context, _a1 string, _a2 *aws_manager.DownloadInput, _a3 ...func(*s3manager.Downloader)) (int64, error) {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, *aws_manager.DownloadInput, ...func(*s3manager.Downloader)) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *aws_manager.DownloadInput, ...func(*s3manager.Downloader)) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: _a0, _a1, _a2
func (_m *AwsManagerInterface) Upload(_a0 context.Context, _a1 *aws_manager.UploadInput, _a2 ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *s3manager.UploadOutput
	if rf, ok := ret.Get(0).(func(context.Context, *aws_manager.UploadInput, ...func(*s3manager.Uploader)) *s3manager.UploadOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3manager.UploadOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *aws_manager.UploadInput, ...func(*s3manager.Uploader)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
