// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import internal "github.com/paysuper/paysuper-management-api/internal"
import mock "github.com/stretchr/testify/mock"

// S3ClientInterface is an autogenerated mock type for the S3ClientInterface type
type S3ClientInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *S3ClientInterface) Get(_a0 string, _a1 string, _a2 internal.GetObjectOptions) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, internal.GetObjectOptions) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Put provides a mock function with given fields: _a0, _a1, _a2
func (_m *S3ClientInterface) Put(_a0 string, _a1 string, _a2 internal.PutObjectOptions) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string, internal.PutObjectOptions) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, internal.PutObjectOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveObject provides a mock function with given fields: _a0
func (_m *S3ClientInterface) RemoveObject(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
